server:
  port: 8765
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zanqian?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:
#mybatis-plus配置
mybatis-plus:
  #mapper.xml文件的路径
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: false
    db-config:
      #全局默认主键自增
      id-type: ASSIGN_UUID
      #全局配置表前缀
      table-prefix: zq_
      #全局逻辑删除的实体字段名
      logic-delete-field: deleted
      #逻辑已删除值(默认为 1)
      logic-delete-value: 1
      #逻辑未删除值(默认为 0)
      logic-not-delete-value: 0